# default: &default
#   protocol: 'https'
#   host: sample.cloudant.com
#   port: 443
#   username: test
#   password: user
#   prefix: project
#   suffix: dev

development:
  suffix: dev

test:
  suffix: test

production:
